### ISSUE TITLE
Getting errors on flutter_rust_bridge v2.0.0-dev.27

### ISSUE THREAD

**Issue by oxyo** [MnlPhlp/flutter_logger#1]
This library not working any more with latest [flutter_rust_bridge](https://github.com/fzyzcjy/flutter_rust_bridge) v2.0.0-dev.27 

after initialization in simple.rs:

```
 flutter_logger::flutter_logger_init!(); 

#[flutter_rust_bridge::frb()]
pub fn test(i: i32) {
    // using the 'log' crate macros
    info!("test called with: {i}")
}


#[flutter_rust_bridge::frb(sync)] // Synchronous mode for simplicity of the demo
pub fn greet(name: String) -> String {
    format!("Hello {name}!")
}

...

```

Getting these errors:

```
error[E0432]: unresolved import `log`
 --> src/api/simple.rs:3:1
  |
3 | flutter_logger::flutter_logger_init!(); 
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ use of undeclared crate or module `log`
  |
  = note: this error originates in the macro `$crate::flutter_logger_init` which comes from the expansion of the macro `flutter_logger::flutter_logger_init` (in Nightly builds, run with -Z macro-backtrace for more info)

error: cannot find macro `info` in this scope
 --> src/api/simple.rs:5:1
  |
5 | #[flutter_rust_bridge::frb()]
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: this error originates in the attribute macro `flutter_rust_bridge::frb` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0433]: failed to resolve: use of undeclared crate or module `log`
 --> src/api/simple.rs:3:1
  |
3 | flutter_logger::flutter_logger_init!(); 
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ use of undeclared crate or module `log```
```

**Comment by MnlPhlp** [comment]
This sounds like you are missing the log crate in your projectes cargo.toml
It should have nothing to do with flutter_rust_bridge or flutter_logger versions

**Comment by MnlPhlp** [comment]
I just updated the example/test in this repo to the newest flutter_rust_bridge and it works

**Comment by oxyo** [comment]
Thank you Manuel for quick reply, I will try again today and will report you back about results.

**Comment by oxyo** [comment]
Hi Manuel, so I just installed flutter_rust_bridge and flutter_logger into a fresh new computer with latest Rust, Cargo and flutter.

here is my cargo.toml from flutter_rust_bridge demo app :

```
[package]
name = "rust_lib_my_app"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
flutter_rust_bridge = "=2.0.0-dev.27"
log = "0.4.21"
flutter_logger = "0.6.0"
```

here is my simple.rs:

```
use log::info;
use log::LevelFilter;
use flutter_logger::flutter_logger_init;

flutter_logger_init!(info_logger, LevelFilter::Info);

#[flutter_rust_bridge::frb(sync)]
pub fn test(i: i32) {
    // using the 'log' crate macros
    info!("test called with: {i}")
}


#[flutter_rust_bridge::frb(sync)] // Synchronous mode for simplicity of the demo
pub fn greet(name: String) -> String {
    format!("Hello, {name}!")
}

#[flutter_rust_bridge::frb(init)]
pub fn init_app() {
    // Default utilities - feel free to customize
    flutter_rust_bridge::setup_default_user_utils();
}

```

and result with errors after cargo build step:

Compiling rust_lib_my_app v0.1.0 (/home/oxyo/projects/flutter/my_app/rust)
error[E0599]: the method `add` exists for reference `&StreamSink<LogEntry>`, but its trait bounds were not satisfied
  --> src/api/simple.rs:5:1
   |
5  | flutter_logger_init!(info_logger, LevelFilter::Info);
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ method cannot be called on `&StreamSink<LogEntry>` due to unsatisfied trait bounds
   |
  ::: /home/oxyo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/flutter_logger-0.6.0/src/logger.rs:7:1
   |
7  | pub struct LogEntry {
   | ------------------- doesn't satisfy `LogEntry: SseEncode`
   |
note: trait bound `LogEntry: SseEncode` was not satisfied
  --> src/frb_generated.rs:28:1
   |
28 | / flutter_rust_bridge::frb_generated_boilerplate!(
29 | |     default_stream_sink_codec = SseCodec,
30 | |     default_rust_opaque = RustOpaqueMoi,
31 | |     default_rust_auto_opaque = RustAutoOpaqueMoi,
32 | | );
   | | ^ unsatisfied trait bound introduced here
   | |_|
   | 
   = note: this error originates in the macro `flutter_logger_init` which comes from the expansion of the macro `flutter_rust_bridge::frb_generated_boilerplate` (in Nightly builds, run with -Z macro-backtrace for more info)

For more information about this error, try `rustc --explain E0599`.
error: could not compile `rust_lib_my_app` (lib) due to 1 previous error

So, maybe I missed something...

**Comment by MnlPhlp** [comment]
Did you run the code generator after modifying the code? I think I got this error after forgetting that
```bash
flutter_rust_bridge_codegen generate
```
 see: https://cjycode.com/flutter_rust_bridge/quickstart#4-modify-it

**Comment by oxyo** [comment]
yes 
`flutter_rust_bridge_codegen generate`
helped, so rust part now works fine

now I have found mistakes in your readme page example code. Please change this:

```
void setupLogger(){
    setupLogStream().listen((msg){
    // This should use a logging framework in real applications
        print("${msg.logLevel} ${msg.lbl.padRight(8)}: ${msg.msg}");
    });
}

void main(){
    await RustLib.init();
    await setupLogger();
    await test(i: 5);
}

```
to this:

```
Future setupLogger() async {
    infoLogger().listen((msg){
    // This should use a logging framework in real applications
        print("${msg.logLevel} ${msg.lbl.padRight(8)}: ${msg.msg}");
    });
}

void main() async {
  await RustLib.init();
  await setupLogger();
  test(i: 5);
  runApp(const MyApp());
}
```

test function is synchronous, so not running with await.

Thank you Manuel for this library :)

**Comment by MnlPhlp** [comment]
Thank you for the hint.
Wouldn't the right solution be to just remove the await?
The function doesn't need to be async.

**Comment by MnlPhlp** [comment]
For some reason it only works with async await. I wonder why this is because there is no await in the setup  function.
I made the changes and will close this issue.
